### ISSUE TITLE
[BUG] compatibility minimum states v9 but missing required v9 manifest fields

### ISSUE THREAD

**Issue by rikmarais** [p4535992/foundryvtt-scene-transitions#1]
**Module Version:** v0.4.3
The 0.4 versions of the module state minimum compatibility v9 but do not include the `name` field which is required to be recognized in v9
https://foundryvtt.com/article/manifest-migration-guide/

It should be boosted to `minimum`: "10"

**Comment by p4535992** [comment]
fixed with next release
