### ISSUE TITLE
Text editing still an issue with 0.4.6 [BUG]

### ISSUE THREAD

**Issue by Meliath1742** [p4535992/foundryvtt-scene-transitions#12]
After updating from The Forge to 0.4.6 discovered that when I tried to edit existing text, as soon as I clicked into the text block all the pre-existing text disappeared. Started over, replaced the text, tried to save and close, but it wouldn't close the edit window. Manually closed the window and opened it back up under the edit function. Text was there but once again, as soon as I clicked into the text block the text disappeared.

**Comment by RavenknightDM** [comment]
Can confirm this bug. Happens any time I try to save and close the editing window. Even if I only try to update any of the checkboxes.

**Comment by p4535992** [comment]
Try out 0.4.7 and let me know it seem to work to me now.

**Comment by RavenknightDM** [comment]
Thanks! Works just fine now.
