### ISSUE TITLE
[BUG] - Cannot save or preview transitions

### ISSUE THREAD

**Issue by bradleyquinn** [p4535992/foundryvtt-scene-transitions#13]
**Module Version:** v0.4.6

**Describe the bug**
When attempting to create a new transition, an error is thrown, the form will not close, and nothing is saved.

**To Reproduce**
Right click map
Create Transition
Save

**Expected behavior**
Form closes and transition saves

**Screenshots**
![image](https://user-images.githubusercontent.com/19616811/208216773-4a66dd1b-f448-40b5-9d2f-d7bebfd2b765.png).

**Browser:**
 Chrome

**Foundry Version:** 
v10 Build 291
**Game System:** 
DND5e 2.0.3

**Comment by Mellowub** [comment]
I'm indeed getting this problem as well, can't save or preview at all, using the actual FoundryVTT software, and can't click save/close/x button to close/save it.

**Comment by DeadlyDan1995** [comment]
Getting the exact same thing, without fail, every time.

**Comment by altair984** [comment]
look the image to fix that error

![imagen](https://user-images.githubusercontent.com/52784850/209231349-c5cbcb4b-665b-4069-9d19-cba9bff26a1d.png)

**Comment by DeadlyDan1995** [comment]
Will give this a try thanks @altair984

**Comment by DeadlyDan1995** [comment]
That fix seemed to remove the error, but now the scene transition doesn't seem to play at all and I get this yellow error.
![image](https://user-images.githubusercontent.com/121134035/209471240-2629aadb-5ec6-441c-90f0-5b71f07743ec.png)

**Comment by sroakjp** [comment]
I'm getting similar behavior. The error I'm seeing is this:
![image](https://user-images.githubusercontent.com/62338951/209755933-c4590bee-5b60-4674-bc57-a72cda194875.png)

**Comment by gaaaork** [comment]
Exactly the same problems.

**Comment by altair984** [comment]
Hi, I'm very sorry that everything is not solved, although I find it strange because it fixes everything for me. Have you updated foundry to the latest version?

**Comment by gaaaork** [comment]
FVTT build (stable) 10,291
Scene transition 0,4,6

The bug is there since 2 or 3 weeks (i think).

**Comment by ctbritt** [comment]
yup. I'm having the same issue. I made the changes you suggested @altair984, but it's not playing the transition and giving me the same error as @DeadlyDan1995.

**Comment by V3rotti** [comment]
Same Issue on my side
![image](https://user-images.githubusercontent.com/56869989/210808979-4026c65e-0fa9-400c-858e-d6ba4fc7f667.png)

**Comment by Chadnic** [comment]
Fixing the script as recommended above to add the missing .options works fine for me.  Everything is working as expected so far after installing it for the first time but I haven't tried every option quite yet.

Link to fix: [https://github.com/p4535992/foundryvtt-scene-transitions/issues/13#issuecomment-1363377797](url)

**Comment by Burzghash** [comment]
I added the 'options' text to both lines 323 and 324 of the indicated file, and while I can now save and close the scene transition's options, I'm still having the error message below and transitions still do not work. Shame, really hope the author gets around to addressing this.

![em](https://user-images.githubusercontent.com/62590854/211095251-0d1968d0-63b1-492c-b5ac-b5bf22dc4559.jpg)

**Comment by coffiarts** [comment]
Exact same issue for me, using Foundry 10.219.
Any fix in sight yet?

**Comment by ArthurCVI** [comment]
I can also confirm this issue.
Everything is updated. I haven't applied the suggested solution, as I'm playing/building on Forge.
I would be happy to give more information to get this issue resolved.
Looks like a great module, but unfortunately not usable for me at the moment. I'm using plenty of different modules… maybe an incompatibility?

**Comment by Candarin** [comment]
Also seeing the same issue. Modified the code as per altair984 and then had success. Still awaiting official release to properly rectify though.

**Comment by Burzghash** [comment]
After having no luck with the proposed fix above, I went browsing for other bugs and found that I also had this one occurring as well:
[https://github.com/p4535992/foundryvtt-scene-transitions/issues/10](url)

After unchecking all of the "Don't show in other GM windows" options for all my transitions, they now sort-of work (there's some minor annoying behavior still).

**Comment by coffiarts** [comment]
> After unchecking all of the "Don't show in other GM windows" options for all my transitions, they now sort-of work (there's some minor annoying behavior still).

For me this doesn't make a difference: My scene transitions window never manages to save or close, no matter which options I enable or disable. It seems to me that these are two separate issues indeed.

**Comment by ArthurCVI** [comment]
Glad to hear that the two fixes work for you. Too bad I can't add them to Forge so easily. Hope that this can be integrated permanently at the next opportunity.

**Comment by Chadnic** [comment]
As I mentioned previously, mine works fine, without issue after doing the two line changes.  

Two caveats:

1.  I am running this locally, not on a third party (say Forge for example)
2. I am using the following settings:
<img width="329" alt="Settings for Transitions" src="https://user-images.githubusercontent.com/36252336/211419162-fb9b2e7c-b129-4fb0-a932-6b1dedf7725d.png">

**Comment by chewey57** [comment]
> Glad to hear that the two fixes work for you. Too bad I can't add them to Forge so easily. Hope that this can be integrated permanently at the next opportunity.

If you download the package and follow the instructions here: https://forums.forge-vtt.com/docs?topic=10510 you can install a custom version of this module that you make yourself. I would recommend installing your custom version alongside the original because it doesn't work otherwise. I'm not smart enough to figure out why.

Once you enable both modules, and you right click the scene you will see controls replicated:
![image](https://user-images.githubusercontent.com/123044073/213352239-3e5eb5ee-eeaa-4b92-815e-94f92000475b.png)

You'll have to experiment to see which one works, but it's a work-around until the master branch is updated.

**Comment by p4535992** [comment]
Thank you all for your interest in the module as you have seen I have not been around much for this module. The issue should be resolved, but let me know.

**Comment by coffiarts** [comment]
> The issue should be resolved, but let me know.
> Special ty to @chewey57 for the PR really appreciate it the help
I can confirm that the new version works fine for me!

**Comment by Candarin** [comment]
Issue is resolved for me. I can edit scene transitions successfully, and save and close the modal. Thanks @p4535992

**Comment by sroakjp** [comment]
I can now edit and save transitions, but they won't play. When I play a transition, it gives me the blue scene loading bar, but and then just stays on whatever map I was looking at. No scene transition. Unfortunately, I don't get any warnings or errors that would explain this.

**Comment by chewey57** [comment]
@sroakjp make sure "Don't Show other GM windows" is not checked.

**Comment by sroakjp** [comment]
> @sroakjp make sure "Don't Show other GM windows" is not checked.

Tried that. Same result. Still not working.

**Comment by ArthurCVI** [comment]
> > @sroakjp make sure "Don't Show other GM windows" is not checked.
> 
> Tried that. Same result. Still not working.

I can confirm this. Probably a new issue. I have the exact same behavior as described by @sroakjp 
Haven't checked the console yet for any errors. I will check that later today.

**Comment by DeadlyDan1995** [comment]
I am still getting nothing happening on the scene transition too, the blue bar goes across the screen (like you are preloading the scene) but nothing happens. I am getting this error from something though, if this helps...
![image](https://user-images.githubusercontent.com/121134035/213916139-b0f3f58b-f979-4b9f-b9f8-cb430d791f11.png)

**Comment by sroakjp** [comment]
> I am still getting nothing happening on the scene transition too, the blue bar goes across the screen (like you are preloading the scene) but nothing happens. I am getting this error from something though, if this helps... ![image](https://user-images.githubusercontent.com/121134035/213916139-b0f3f58b-f979-4b9f-b9f8-cb430d791f11.png)

This is the exact behaviour I am seeing, but I don't recall seeing that error.

**Comment by p4535992** [comment]
Try out 0.4.11 and let me know it if the issue persist

**Comment by chewey57** [comment]
Works for me, though I didn't have the same issue. If this doesn't work, one thing I did do was blow-away all my transitions and make them again.  Thanks @p4535992 for continuing to support this module!

**Comment by sroakjp** [comment]
The issue does persist. But I also tried deleting and recreating one of my transitions and that one worked. So maybe I need to rebuild all of my transitions.

**Comment by DeadlyDan1995** [comment]
Not sure if this is still in development but I have tried deleting transitions and remaking, uninstalling the module and reinstalling and the issues still seem to persist.

**Comment by DeadlyDan1995** [comment]
> what browser are you using ?

Foundry v10 Application

**Comment by p4535992** [comment]
Foundryvtt is the VTT cliwnt with a embedded browser but is not a real browser can you confirm the issue on chrome ?
