### ISSUE TITLE
Can't get the macro to work

### ISSUE THREAD

**Issue by arcanjl** [p4535992/foundryvtt-scene-transitions#19]
I just copied and pasted it, added the image, and when I click run, nothing. 

Macro: 

game.modules.get('scene-transitions').api.macro({
	sceneID: false, // To play a transition without a scene activation, simple pass `false` as the sceneID in the data object or use the string id of the scene.
	content:"Fewmaster Gholcag...",
	fontColor:'#ffffff',
	fontSize:'28px',
	bgImg:'ddb-images/adventures/Dragonlance__Shadow_of_the_Dragon_Queen/assets/03-010.fewmaster-gholcag.png', // pass any relative or absolute image or video url here.
	bgPos:'center center',
    bgLoop: true, // Only for VIDEO, if true will loop the video
	bgMuted: true, // Only for VIDEO, if true will play the video muted
	bgSize:'cover',
	bgColor:'#333333',
	bgOpacity:0.7,
	fadeIn: 400, //how long to fade in
	delay:5000, //how long for transition to stay up
	fadeOut: 400, //how long to fade out
	audio: "", //path to audio file, NOTE: is not advisable to use this with a video and the property 'bgMuted = false'
	skippable:true, //Allows players to skip transition with a click before delay runs out.
    audioLoop: true, //Loop the audio file ?
	gmHide: true, // hide the transition on other windows logged in as a GM
	gmEndAll: true, // when the GM clicks to end the transition - end for everyone
	showUI: false, // Show the User Interface elements to all players allowing them to interact with character sheets etc
	activateScene: false, // Activate the scene when play the transation ?
	fromSocket: false, // This is usually a application variable for manage socket calls YOU DIDN'T NEED TO TOUCH THIS, MUST BE ALWAYS FALSE.
	users: [], // show the transaction to this list of users ids, NOTE: if 'showMe' is true the current user id is add to the list
}, true ); // show to the triggering user (the one who click to the macro usually the GM)

**Comment by p4535992** [comment]
enable the debug module setting and click f12 and show to me if there is any red messages

**Comment by arcanjl** [comment]
Ok, found the issue thanks to the debug. Too embarrassed to state what it was.
I see that the size is "cover" what other options are there for "bgSize"? My image is way too big

**Comment by p4535992** [comment]
can you pass to me the image for some test ?

**Comment by arcanjl** [comment]
Never mind, just put in 500px and it worked

**Comment by arcanjl** [comment]
also % works, do you still want it? I just didn't know what to put in there :)

**Comment by p4535992** [comment]
no if you find a solution no problem, but if you have some advise for a better documentation write some line here.
