### ISSUE TITLE
Option for the sound to not loop

### ISSUE THREAD

**Issue by jacksands** [p4535992/foundryvtt-scene-transitions#2]
Hi! thanks for the module, has been using if forever!

If I can ask, may you add an option for the audio to not loop, sometimes I want a transition to take more time than the audio, and it loops....

and if possible a delay for the Audio to start, fade changes the volume, but do not hold the start.. I use a lot your module with animated png to make mini intros!

by the way, what are the code for fade options for audio in macros?

sorry.. too much alredy!

tks for the amazing module!

**Comment by p4535992** [comment]
Yes you're right it's a bit too much stuff for a module that I just took in "maintenance", with version 0.4.4 I added the option to loop the audio which was a simple thing, but for your use case maybe it's better to convert the images directly to video (I recommend the webm format) and associate the video with the audio (even multi-track) you want, fading with effects with one of the many free tools you find on the web, there are hundreds of them and I couldn't advise you which one is better than another.

I have added two options to help you the "Video Loop" and the "Video Muted."

Also let me know about the tool you have chosen for video editing.

**Comment by jacksands** [comment]
not a problem at all, I really love your module, for scene load, effects, it is amazing to use with monk active tiles triggering your module for an effect and so on..
by your suggestion I found Media share that have an immersive full screen video for players, but no macro to start it...   but I can handle it. the result was quite good.

I use kdenlive for video editing for some time..

anyway thanks for the module... I lost count of who many times I had wow my players with it!!

tks!!!
