### ISSUE TITLE
[BUG] Unable to install module on Foundry v11 Build 299 local instance

### ISSUE THREAD

**Issue by chewey57** [p4535992/foundryvtt-scene-transitions#22]
**Module Version:** v0.3.0

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
Unable to install module to Foundry Version 11 Build 299. The following error appears: Error: Unable to load valid module from "https://raw.githubusercontent.com/DM-miX/scen-transitions/master/module.json" Module validations errors: authors: 0: name: may not be undefined

**To Reproduce**
1. Open Foundry v11 build 299 on your desktop/server
2. Click on "Add on Modules"
3. Click on "Install Module"
4. Search for "Scene Transitions"
5. Click on "Install"
7. See error

**Expected behavior**
The Module was installed

**Screenshots**
![image](https://github.com/p4535992/foundryvtt-scene-transitions/assets/123044073/73c2a104-2375-4252-a99a-b7963f1ed679)
**Browser:**
 - 

**Foundry Version: 11 Build 299

**Game System: N/A

**Additional context**
N/A

**Comment by coffiarts** [comment]
Still no news on that? Since upgrading to Foundry 11, I haven't been able to use scene-transitions anymore.

**Comment by coffiarts** [comment]
It's weird (is it only in my game?). Downloading the zip from the latest release (https://github.com/p4535992/foundryvtt-scene-transitions/releases/download/v0.4.12/module.zip) directly and unzipping it to the modules dir seems to bypass the above error. 
It shows up in the list of installed modules in setup.
But still I can't get it to show up in the modules list in game (which means that I can't enable it). Strangely, there are no console errors at all related to this mod (at least I can't detect any).
What's happened to this (beloved) mod? Has it gone into zombie state? ;-)
Any help highly appreciated! I don't want to miss scene-transitions in my game :-(

**Comment by uniwars** [comment]
+1

**Comment by coffiarts** [comment]
Just another idea....
Out of curiosity, I ran an auto-formatting of the module.json in IntelliJ (CTRL+SHIFT+L), and it apparently changed every single line start, replacing tabs by spaces.
I am no json academic, so I am uncertain whether the original tabbed version may be invalid (I hat thought that tabs are valid in JSON). But it may still be a strong hint that something is malformed in the module.json.
It's a quickshot guess, and I can't test it locally, so I don't want to create a pull request just based on that guess.
But it may be a starting point for a fix?

Original:
![image](https://github.com/p4535992/foundryvtt-scene-transitions/assets/39616483/42b320e2-3b97-4bf8-a5de-abbe186ff0b7)

After auto-format:
![image](https://github.com/p4535992/foundryvtt-scene-transitions/assets/39616483/5bd0a792-662c-482d-a37f-86bea9ea0b6f)
