### ISSUE TITLE
When Activation Scene change through Transitions it does not load. [BUG]

### ISSUE THREAD

**Issue by mussja28** [p4535992/foundryvtt-scene-transitions#25]
**Module Version:** v0.0.0

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
Inconsistency with scene transitions using this mod. When attempting to change scenes players are prompted by permission problems. If a playlist is set to play on the scene they are arriving on they get "lacks permission to update playlist" or even with that removed they get "lacks permission to update scene." Now I've created a scene today and the scene transition works, but these scenes that are having issues are all of the scenes I created prior to installing this mod. I even tested duplicating the problematic scenes and seeing if their duplicate had the same issue, which it does.

**To Reproduce**
1. Install.
2. Create a transition and select "Activate Scene for Everyone" at the bottom of the settings.
3. Activate Scene
4. See error from player's side.

**Expected behavior**
No where in the instructions did it mention anything about permissions and even watched a video on the setup of this, but I would have expected the transition to play and the players to transition to the new scene since I selected "Activate Scene for everyone" but when I do players get the prompt "Cannot edit the scene" permissions error. I do not know why.

**Screenshots**
![image](https://github.com/p4535992/foundryvtt-scene-transitions/assets/137832669/3e1c6e38-a702-4e67-938f-11c51fd6d6cf)
![image](https://github.com/p4535992/foundryvtt-scene-transitions/assets/137832669/92af0264-a54b-46fc-8d10-d220264588de)

**Browser: Any**
 - 

**Foundry Version: v10.291** 

**Game System: DnD5e = Fifth Edition System v2.2.2** 

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by mussja28** [comment]
Okay I've gotten a least some kind of solution to the issue. Which is unchecking the "Don't Show other GM Windows" with that unselected it tries to take me (the GM) along with the players to the activated scene. The only catch is I have to activate it twice. The first time doesn't take me with but the second time I go along with no problem and the players come with in this case.

So, I think there's a bit of a solution, but players still get the "lacks permission" warning if I don't activate it a second time. The problem doesn't kick back any errors on the DM's side only on the player's side.

**Comment by teltzs** [comment]
@p4535992 Bump - I am also having this issue.

**Comment by Mad7eo** [comment]
> @p4535992 Bump - I am also having this issue.

Same issue with me
