### ISSUE TITLE
[BUG] Video does not play first time

### ISSUE THREAD

**Issue by RYGUY722** [p4535992/foundryvtt-scene-transitions#26]
**Module Version:** v0.5.0

Sadly this is a bug where the module believes it is functioning correctly, so there are no logs to attach. There will be a few screenshots of what I _believe_ to be the culprit however, and I've recorded a quick video showing my exact issue in action.

**Background**
I understand this isn't exactly the intended usage of this module, but I've been using this module for its fullscreen video to show cutscenes to my players. The campaign is based on another game, so prerendered recordings of it help communicate ideas in a way my tabletop representation can't. Being able to show these videos in a timely manner without major glitches would be really nice.

**Describe the bug**
I'm having an issue where videos will not play the first time the transition is triggered. The audio, which is set to the same video (I've found it's increased the consistency in which the video will work properly) plays just fine on the first load, but the video is simply nowhere to be seen. On the second load of the video, everything _seems_ to work fine, at least. After extensive testing between myself and one of my players, I believe this is caused by div style blocks suddenly being populated only on the second load. As you can see down in the Screenshots section, the first playthrough lacks the style portions of the relevant divs. Once the transition begins the second time, these are filled properly with all the options I filled out in the macro.

**To Reproduce**
1. Attempt to show video transition
2. Audio plays, but the screen overlay does not
3. Try again
4. ???
5. Profit

**Expected behavior**
I've already built in a 10 second wait, so I'd really like the video to play the first time if possible.

**Screenshots**
During the first playthrough:
![image](https://github.com/p4535992/foundryvtt-scene-transitions/assets/14841926/a8f0d376-e937-4225-9fda-c0db12d78380)
During the second playthrough:
![image](https://github.com/p4535992/foundryvtt-scene-transitions/assets/14841926/3b285bdd-ea4c-4caa-905d-222ed33b9247)

**Browser:**
 This has occurred both in the Foundry client itself and every Chromium based browser I've tried it in. If it's believed the exact browser is the issue, I can reach out to each of my testers and ask for their browser of choice.

**Foundry Version:** 
11, Build 315

**Game System:** 
Custom System Builder

**Additional context**
I've recorded the issue and uploaded it in an unlisted video [here](https://youtu.be/U54YaRzvUdQ). I will warn you to brace your ears before watching, as my computer is not a quiet one and it is sadly picked up by the microphone and OBS very well.

**Comment by JustLikeAMetaphor** [comment]
Everyone in my Forge-hosted game experiences this as well. Same symptoms, all of them using Chrome. I would like to share a workaround that may help until this is patched.

Using the API macro activation, you can create a 'primer' macro that will get that first false start out of the way for everyone connected to the game, which I will share below. After hitting the macro, you can then use the same video as a scene transition normally and it will work for everyone until they disconnect from Foundry.

The first time you click the macro, nobody in the game (Including you) will see anything at all. The second time its used, connected users will only see a very brief flicker. This can jumpscare people a little, but it's as unobtrusive as I could make it so it can be used with mixed groups of already-primed and unprimed users.

The video file in the primer macro must be the same as the transition you are going to play next. If you use a different video in your next transition, it will ignore whatever video you selected and play the video from the primer macro. So its a bit cumbersome. But hey, your cutscenes/transitions will work when it counts.

```game.modules.get('scene-transitions').api.macro({
    sceneID: false, // To play a transition without a scene activation, simple pass `false` as the sceneID in the data object or use the string id of the scene.
    content:"",
    fontColor:'#ffffff',
    fontSize:'28px',
    bgImg:'VIDEO URL FOR NEXT TRANSITION', // pass any relative or absolute image or video url here.
    bgPos:'center center',
    bgLoop: false, // Only for VIDEO, if true will loop the video
    bgMuted: true, // Only for VIDEO, if true will play the video muted
    bgSize:'cover',
    bgColor:'#000000',
    bgOpacity:0.0,
    fadeIn: 0, //how long to fade in
    delay:1, //how long for transition to stay up
    fadeOut: 0, //how long to fade out
    audio: "", //path to audio file, NOTE: is not advisable to use this with a video and the property 'bgMuted = false'
    skippable:true, //Allows players to skip transition with a click before delay runs out.
    audioLoop: false, //Loop the audio file ?
    gmHide: false, // hide the transition on other windows logged in as a GM
    gmEndAll: true, // when the GM clicks to end the transition - end for everyone
    showUI: false, // Show the User Interface elements to all players allowing them to interact with character sheets etc
    activateScene: false, // Activate the scene when play the transation ?
    fromSocket: false, // This is usually a application variable for manage socket calls YOU DIDN'T NEED TO TOUCH THIS, MUST BE ALWAYS FALSE.
    users: [], // show the transaction to this list of users ids, NOTE: if 'showMe' is true the current user id is add to the list
}, true ); // show to the triggering user (the one who click to the macro usually the GM)```

**Comment by RYGUY722** [comment]
Hey, bit late on the reply here, but I appreciate the help @JustLikeAMetaphor! I actually already went and made a similar macro of my own that helps me out with that. It takes a bit more work to get ready, but it's nicer looking than having a bunch of primer macros, so I figured I'd share it in case anyone else is having trouble with this issue. 

In order to make my picker macro work, you need all your video macros in a single folder and they need to look something like this:
```js
const vid = '[VIDEO URL]';
const duration = [DURATION HERE];
const vol = (scope.load ? 0 : 1);

// await new Promise(resolve => setTimeout(resolve, 5000));

game.modules.get('scene-transitions').api.macro({
	sceneID: false,
	content:"",
	fontColor:'#ffffff',
	fontSize:'28px',
	bgImg: vid,
	bgPos:'center center',
        bgLoop: true,
	bgMuted: true, 
	bgSize:'cover',
	bgColor:'#333333',
	bgOpacity: (scope.load ? 1 : 0),
	fadeIn: 100,
	delay: (scope.load ? 500 : duration),
	fadeOut: 100,
	audio: vid,
        volume: vol,
	skippable: false,
        audioLoop: false,
	gmHide: false,
	gmEndAll: true,
	showUI: false, 
        activateScene: false,
	fromSocket: false, 
	users: []
}, true );
```

Then, the actual picker macro, which I modified an older song picker macro from someone to get to, is:
```js
let playlistOptions = game.folders.get('[FOLDER ID GOES HERE]').contents.reduce((acc,p) => acc += `<option value="${p.id}"> ${p.name}</option>`,``);
const content = `<form>
                    <div class="form-group">
                        <label>
                            Animation:
                        </label>
                        <select name="list">${playlistOptions}</select>
                    </div>
                    
                 </form>`;
new Dialog({
    title: "Select Macro to Play",
    content,
    buttons: {
        load: {
            label: "Load",
            callback: (html)=> {
                let mid = html.find("[name=list]")[0].value;
                game.macros.get(mid).execute({load: true});
            },
            icon: '<i class="fas fa-save"></i>'
        },
        play: {
            label: "Play",
            callback: (html)=> {
                let mid = html.find("[name=list]")[0].value;
                game.macros.get(mid).execute({load: false});
            },
            icon: '<i class="fas fa-play"></i>'
        }
    }
}).render(true);
```

This'll pop up a dialog with a dropdown for you to pick which macro to play, then 2 buttons to choose between loading it in and actually playing it. I think this follows the same idea as your loading macro, it just does it in a way that's slightly better for if you have a bunch of different videos you'd like to play.
