### ISSUE TITLE
Typo in `src/templates/transition-form.html`

### ISSUE THREAD

**Issue by samburba** [p4535992/foundryvtt-scene-transitions#3]
Hello! There is a slight typo in `src/templates/transition-form.html`. The current text reads:
```html
<p class="notes">Allow players to interact woth character sheets etc</p>
```
which should be:
```html
<p class="notes">Allow players to interact with character sheets etc.</p>
```
on line [128](https://github.com/p4535992/foundryvtt-scene-transitions/blob/2a510a3b9e0aed12aaa71124d3350746cd4025ef/src/templates/transition-form.html#L128).

Great module by the way!

**Comment by p4535992** [comment]
fixed with next release
