### ISSUE TITLE
What are the accepted parameters for bgSize?

### ISSUE THREAD

**Issue by charles-large** [p4535992/foundryvtt-scene-transitions#34]
I am trying to make the transition images not 'cover' the entire screen as they are being stretched and cut off. Is there an alternative value for bgSize that would be accepted? I have tried just setting a number (eg: 1000) and dimensions (eg: 1920x1080), but it has not changed the result. Not sure if I am missing something or right now this functionality does not exist.

**Comment by Larkinabout** [comment]
It sets the `background-size` style, so you can use this a reference: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size
