### ISSUE TITLE
[BUG] Upgrading module for v12

### ISSUE THREAD

**Issue by TerabyteRex** [p4535992/foundryvtt-scene-transitions#35]
**Module Version:** v0.5.3

**Foundry Version**
v12

Ther have been changes to the manifest for v12. I will make the changes like I did for v11. There are a few more changes so I want to take time to read through and assess the impact. creating this bug to help me track.

**Comment by p4535992** [comment]
Little free time to devote to my hobby...but if you find time to test the module on v12 and tell me it doesn't “break” or damage worlds (excluding known bugs) I have no problem editing the json manifest.

**Comment by TerabyteRex** [comment]
bad ass. i have been swamped and thisissue has been a voice in my head. "haha you fidnt fix it today". coding issues haint me :)
