### ISSUE TITLE
[BUG] Foundry v11 (electron client only): Worlds/scenes won't load at all after upgrade to v5.5.

### ISSUE THREAD

**Issue by coffiarts** [p4535992/foundryvtt-scene-transitions#37]
**Module Version:** v0.5.5 (latest)

**Before open any issue**
Here's my log (following steps 1 through 5).
[foundry-v11.315.log](https://github.com/user-attachments/files/15827727/foundry-v11.315.log)

**Describe the bug**
After upgrading from v0.5.3 to v0.5.5, my worlds (more precisely: the first scene of any world) do not load up anymore.
I only get grey backgrounds (see screenshot). Even after 10 minutes of waiting, nothing happens.
The log attached does not seem to show _any_output at all from scene-transitions.

I've made sure before, while v0.5.3 was still installed and running fine, that both the module and the enable_debugging option are activated.

I can consistently reproduce this ...
- on  Foundry 11.315 (electron client)
- on two different game systems (dnd5 3.2.0  and tde5 5.4.5)
- in absolutely clean worlds, where no module other than scene-transitions is active
- while logged in as the gamemaster as well as a player

But finally...
- In Chrome it works
- When downgrading to v0.5.3, everything (in any of the above setups) works again in v11 electron client.
- in comparison, in Foundry **v12**'s electron client, everything works fine even with v0.5.5

**Screenshots**
![image](https://github.com/p4535992/foundryvtt-scene-transitions/assets/39616483/2d0155e6-139b-4fe4-81a8-7d151b6eed54)

**Browser:**
 - Chrome 125.0.6422.142 (though the browser is not the issue here)

**Foundry Version:** 
11.315 (latest 11 version)

**Game System:** 
dnd5 3.2.0
tde5 5.4.5

I am absolutely out of clues here... can anyone else reproduce this?

**Comment by Larkinabout** [comment]
I'll try to have a look when I can. Just to confirm I've understood correctly: Foundry gets stuck when you're on 11.315 with Scene Transitions 0.5.5 but only when you're using the Foundry application? Otherwise it is fine when you use Chrome on those versions?

**Comment by coffiarts** [comment]
[@Larkinabout - Yes, it's exactly like that. Just for completeness, find attached the log from the (sucessful) startup in Chrome.
Thank you very much for looking into it!
[foundry-v11.315_chrome.log](https://github.com/user-attachments/files/15846350/foundry-v11.315_chrome.log)

**Comment by KieranLorray** [comment]
I was having the same issue as well. Technically, it does actually load on my end, just after 2 minutes 16 seconds.

**Comment by coffiarts** [comment]
I have the same impression (that it's just incredibly slow). On my side, though, it won't show up even after 10 minutes.
Nevertheless, I have moved on to v123 in the meantime. I am wondering whether tracking this issue down is still worth it.

**Comment by Trellinane** [comment]
Same issue for me.

**Comment by BrentonPerry** [comment]
I am also having the issue of the client not loading the world with the module enabled. I have waited over 10 minutes as well, and it still does not appear to load. Has the V11 version been abandoned in favor of V12?

**Comment by Larkinabout** [comment]
> I am also having the issue of the client not loading the world with the module enabled. I have waited over 10 minutes as well, and it still does not appear to load. Has the V11 version been abandoned in favor of V12?

No, it was intended to work for both, though I haven't had time to look at the issue caused by the latest release. In the meantime, can you install the previous version, which worked with V11?

**Comment by p4535992** [comment]
Probably fixed , ty to the Larkinaabout hard work.

**Comment by coffiarts** [comment]
Sounds great, thanks for your an @Larkinabout's commitment to this. As mentioned earlier, I've moved on to v12 and can't verify the fix anymore without greater efforts. But I assume that others here will check.

**Comment by BrentonPerry** [comment]
I'm still on V11, and the issue of long loading times and game crashes is fixed. Thank you @Larkinabout.

**Comment by Necrotech242** [comment]
Can confirm everything works in Foundry version 11 Build 315 Thanks for the update!
