### ISSUE TITLE
[BUG] Text behind background image (not visible)

### ISSUE THREAD

**Issue by amcvfx** [p4535992/foundryvtt-scene-transitions#4]
**Module Version:** v2.3.20

**Describe the bug**
I have an issue when creating a scene transition with a background image and text. The text seems to be behind the background image meaning the text won't show when the image is at 1 opacity. This occurs with only the Scene Transitions module active as well.

**Expected behavior**
Could the text be placed on top of the image so it is visible with an image behind it?

FVTT 10.288
DnD5e

**Comment by TomChristoffer** [comment]
I agree with this, this means you can never make the text fully opaque either, it's always semi-transparent since the background image is above it.

**Comment by orcnog** [comment]
+1

**Comment by orcnog** [comment]
this ought to fix it...

![image](https://user-images.githubusercontent.com/70491549/207671047-c03b913d-1d87-434c-8b03-a5534cdf3315.png)

**Comment by p4535992** [comment]
Try out 0.4.5
