### ISSUE TITLE
Are there still builds available for v9?

### ISSUE THREAD

**Issue by ageofmyth** [p4535992/foundryvtt-scene-transitions#5]
Hello there,

Long story short - I'm looking for mod builds for v9 of Foundry, since I haven't updated to v10 yet (and am not planning on updating for a while). Is there still a way to download and install the v9 builds for this mod?

**Comment by p4535992** [comment]
Sorry , there is to  much work on my side for maintain two different branch, you can install the last verified release for 9 here:

https://raw.githubusercontent.com/DM-miX/scene-transitions/master/module.json

**Comment by lbnesquik** [comment]
> Sorry , there is to much work on my side for maintain two different branch, you can install the last verified release for 9 here:
> 
> https://raw.githubusercontent.com/DM-miX/scene-transitions/master/module.json
You should put this in the read me! I almost created another topic! 
Thanks for linking a working link!
