### ISSUE TITLE
[Feature Request] Add an example macro to the compendium

### ISSUE THREAD

**Issue by orcnog** [p4535992/foundryvtt-scene-transitions#8]
I found the example macro in your github readme, but it would have been great it if was already in the compendium for users who don't dabble in code to the _github_ level but don't mind experimenting with _macros_.  If you have any additional macro functionality, adding those macro examples would be much appreciated as well.

Specifically, I'm looking for the ability to run several transitions, with text overlaid, in sequence... like 4 or 5 in a row, as kind of a graphic novel cut scene without loading multiple separate maps to accomplish this.  Any help with that would be greatly appreciated :)  ...but not what this feature request is really about.

**Comment by p4535992** [comment]
Add a example macro on the module if you need more example let me know it
